### PR TITLE
Publish package to PyPi using GitHub action (fixes #25)

### LINKED ISSUE #25: Uploading tagged versions to PyPi
https://github.com/vmalloc/pyforge/pull/24 Move CI from Travis CI to GitHub actions.
the PR run tests but doesn't adds automatic deployment for tags.

I found this actions for uploading python packages (written by Pypa organization):
https://github.com/marketplace/actions/pypi-publish

I never use this action - @vmalloc Do we want to add it to this repository?

### PR DESCRIPTION
**Pull request by ayalash**

### CODE REVIEW

**Comment by ayalash** [comment]
@vmalloc Please merge this PR only after you add `PYPI_API_TOKEN` secret (I don't have permissions on this repo for doing it)

**Comment by vmalloc** [comment]
@ayalash secret added

**Comment by ayalash** [comment]
@vmalloc I've just noticed that this PR is ready for merge, but was forgotten by me.
Can it be merged and then release a new version, so we can be sure that it works?

**Comment by vmalloc** [comment]
I think so. Want me to do it?

**Comment by ayalash** [comment]
I've just merged it, can you just release a version? (I don't think that I have permissions for it)

**Pull request merged**
